### PR TITLE
Merge TesterPage branch files to the main branch

### PR DESCRIPTION
**Pull request by dOo0oOb**
## Summary

Modified files:
TesterPage.react.js added components
yarn.lock added icons-material api and runtime
package.json added icons-material api

Added files:
TesterHeader.react.js added components
TesterRatingScore.react.js added components
TesterReportDialog.react.js added components
TesterReportErrorAlert.react.js added components
TesterRunErrorAlert.react.js added components
TesterStepper.react.js added components
TesterTranscriptionCard.react.js added components
TesterTranscriptionTextField.react.js added components
TesterTranslationCard.react.js added components
TesterTranslationTextField.react.js added components
TesterUploadDialog.react.js added components
TesterUploadErrorAlert.react.js added components
TesterUploadSelect.react.js added components
TesterUploadTextField.react.js added components

## Screenshots
The main Tester Page
image

The Upload Video Pop-up Dialog
image

The Report Pop-up Dialog
image

Error Pop-up for Grammar check
image

Error Pop-up for upload a video
image

Error Pop-up for send a report
image

### CODE REVIEW

**Comment by SPiCaRiA** [comment]
Hi, before I review this PR, a few things need to be noted on your side:

1. For the PR summary, screenshots on code files give no information about how you tested your code... It would be better if you can include how it works on your local machine.
2. Though you mentioned in your summary "ignore changes on analytics page", it is not how Git works. I cannot just ignore the changes on analytics page and approve this review. This is because once the PR is approved, **all changes in this PR** will be merged into the main branch. Please exclude the changes from your PR.
3. Just a nit, but this PR is still a draft PR, and you need to publish it.

**Comment by dOo0oOb** [comment]
1. Added screenshots for testing pages
2. TesterPage branch has documents for Analytics Page. After comparing the documents in the Main and TesterPage branches, there are only minor differences between them. I fixed it in the commit Merge branch 'main' into TesterPage.

**Comment by dOo0oOb** [comment]
Deleted pyvenv

**Comment by dOo0oOb** [comment]
Deleted the screenshots for code

**Comment by dOo0oOb** [comment]
Updated the latest version of Analytics page based on main branch

**Pull request closed without merging**
